const categoriesdata=['Fiction','Poetry','Fantasy','Romance'];
const Allcategories=['ANTIQUES COLLECTIBLES','ARCHITECTURE','BIBLES','TRUE CRIME','TRAVEL','TRANSPORTATION','STUDY AIDS','SOCIAL SCIENCE','SELF-HELP','SCIENCE','RELIGION','POLITICAL SCIENCE','PHOTOGRAPHY','PHILOSOPHY','PETS','PERFORMING ARTS','NATURE','MUSIC','MEDICAL','MATHEMATICS','LITERARY CRITICISM','LITERARY COLLECTIONS','LAW','LANGUAGE ARTS & DISCIPLINES','JUVENILE NONFICTION','JUVENILE FICTION','HUMOR','HOUSE & HOME','HISTORY','DRAMA','COOKING','COMPUTERS','COMICS & GRAPHIC NOVELS','BUSINESS & ECONOMICS']
const Allcategoriesquery=['ANTIQUES+COLLECTIBLES','ARCHITECTURE','BIBLES','TRUE+CRIME','TRAVEL','TRANSPORTATION','STUDY+AIDS','SOCIAL+SCIENCE','SELF-HELP','SCIENCE','RELIGION','POLITICAL+SCIENCE','PHOTOGRAPHY','PHILOSOPHY','PETS','PERFORMING ARTS','NATURE','MUSIC','MEDICAL','MATHEMATICS','LITERARY+CRITICISM','LITERARY+COLLECTIONS','LAW','LANGUAGE+ARTS+&+DISCIPLINES','JUVENILE+NONFICTION','JUVENILE+FICTION','HUMOR','HOUSE+&+HOME','HISTORY','DRAMA','COOKING','COMPUTERS','COMICS+&+GRAPHIC+NOVELS','BUSINESS+&+ECONOMICS']

module.exports={categoriesdata,Allcategories,Allcategoriesquery};



